'use server';

import type { PropsWithChildren } from 'react';
import type { Metadata } from 'next';

import '~/styles/global.css';

import { Body } from '~/components/body/body';
import { ThemeProvider } from '~/global-context/theme';
import { LanguageProvider } from '~/global-context/translation';

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: 'Create Next App',
    description: 'Generated by create next app',
  };
}

export default async function RootLayout({ children }: PropsWithChildren) {
  return (
    <LanguageProvider translations={{}} defaultLanguage={'pt-BR'}>
      <ThemeProvider defaultTheme={'light'}>
        <Body>{children}</Body>
      </ThemeProvider>
    </LanguageProvider>
  );
}
